name: Backend CI/CD

on:
  push:
    paths:
      - 'BE/**'
    branches:
      - main

  pull_request:
    paths:
      - 'BE/**'
    branches:
      - main

jobs:
  backend-ci-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test

      - name: Install Vercel CLI
        run: npm install -g vercel

      # 🚀 Preview Deployments for PRs
      - name: Deploy Backend Preview (PR)
        if: github.event_name == 'pull_request'
        run: vercel deploy \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --scope=${{ secrets.VERCEL_ORG_ID }} \
            --project=${{ secrets.VERCEL_PROJECT_ID_BE }} \
            --yes --confirm

      # 🚀 Production Deployment only on push to main
      - name: Deploy Backend Production (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: vercel deploy --prod \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --scope=${{ secrets.VERCEL_ORG_ID }} \
            --project=${{ secrets.VERCEL_PROJECT_ID_BE }} \
            --yes --confirm
